Fix #2, Improve Recipes#setRecipeStage(String, IIngredient) performance
jaredlll08/RecipeStages pull request #3
Opened 2017-11-24 01:10 UTC by mezz

This fixes #2 and also has some performance improvements.

Before, Stage 5 recipes script in SevTech takes 32.9 seconds
![recipe-stage-before](https://user-images.githubusercontent.com/916092/33191679-9b6d656c-d070-11e7-96ca-181a90c99709.png)

After, Stage 5 recipes script in SevTech takes 1.5 seconds
![recipe-stage-after](https://user-images.githubusercontent.com/916092/33191681-a0557fa6-d070-11e7-97c9-a54b3304a238.png)

The main cost was creating lots of `IItemStack` each time to check for equality, so I added a cache to do it only one time per recipe.
The next cost was from Forge. Calling `ForgeRegistries.RECIPES.getEntries()` actually makes a copy of the whole entry set each time. I get around this by iterating over the cache instead of the forge registry.

2017-11-24 09:31 UTC, jaredlll08 requested changes

2017-11-24 09:31 UTC, jaredlll08 commented on src/main/java/com/blamejared/recipestages/handlers/Recipes.java
> +        if (recipeOutputCache.isEmpty()) {
This is way to early to create a cache, not all mods would have registered their recipes, so what *should* happen is that the ActionSetStage should be changed to accept a (String stage, IIngredient output), and this logic be done in the action (The action is delayed until just before JEI runs, most actions are, it ensures that all the recipes are there)

2017-11-25 00:46 UTC, mezz commented
I have improved the implementation so that it only checks when the action is run.  
Instead of using a cache, it combines all the "recipe output" calls into one action.

2017-11-25 00:59 UTC, jaredlll08 approved these changes

2017-11-25 00:59 UTC, merged